### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by lordbaz1986** [Styyx1/Ruvaak-Readme#19]
Hey, first of all, thank you for making this list.

So I've run through the to do list, but it seems the sheath and unsheath animation aren't playing. the Log says : <ERROR> [Controller] Couldn't extract animation info: Data\Scripts\FNIS_aa2.pex: The system cannot find the file specified.

and I tried to look for FNIS so as to generate behavior, but I am not exactly strong in modding, so could not properly trubleshoot this myself, hence this post.

Thanks in advance, and I hope it allright that I write this.

**Comment by chri3i** [comment]
if you refer to the to-do list in the project (i closed it now) then it's my mistake cause that's done already. I just forgot about the project. But to not leave you empty handed: FNIS isn't used anymore nowadays. or at least very, very rarely used. Nemesis is its better replacment.

**Comment by lordbaz1986** [comment]
Thanks for the answer, yeah tried to use the nemesis, but it
wouldn't/couldn't update the animations. I can write you the message log
from nemesis when i get home if that's allright.
