### ISSUE TITLE
[BUG] Arnbjorn missing arm textures

### ISSUE THREAD

**Issue by xermaran** [Styyx1/Ruvaak-Readme#20]
**Describe the bug**
Arnbjorn(the Dark Brotherhood NPC) has missing arms. 

**To Reproduce**

1. Go to Dark Brotherhood Sanctuary 
2. 
**Screenshots**
![Dark Brotherhood Sanctuary - Fredas, 7꞉20 PM, 29th of Last Seed, 4E 201](https://user-images.githubusercontent.com/13500058/213910922-44e7d734-f75b-40b9-8a24-c6fc4b06e92f.png)

**Modlist version**: 3.1.0

**Did you add any additional mods?** None, no modification

**Comment by Styyx1** [comment]
Fixed in 4.xxx
