### ISSUE TITLE
'[BUG]' "Details" "PLSHELP"

### ISSUE THREAD

**Issue by ZzpercyxX** [Styyx1/Ruvaak-Readme#23]
Word of power doesn't work at Bleak Falls Barrow after defeating the dragon priest and the door leading to outside is locked. So now I'm stuck in at the end of BFB

**Comment by Styyx1** [comment]
The quest definitely works when you proceed through the dungeon by normal means. 
The exit is blocked because there's a mod in the list that blocks the exit, you go back the way you went in
