### ISSUE TITLE
'[BUG]' "Details" “Memories of a vagabond” not working

### ISSUE THREAD

**Issue by cinaedusmortiis** [Styyx1/Ruvaak-Readme#25]
As per previous bug submitted I can confirm I have made no edits to the modlist, all installed via wabbajack and playing current version.

I bought the memories of an archaelogist potion early in my playthrough and was and am able to pick locks in dungeons with this. I then saved up and bought memories of a vagabond, drank it and then forgot about it until I reached a chest in the wild. I couldn’t pick the chest and when I checked the perk tree, the perk had disappeared. 

I thought perhaps I had died and reloaded a save prior to buying memories of a vagabond and forgot, as hadn’t exactly paid attention, so I reloaded an earlier save and tried buying again. I checked after drinking the potion and the perk was there in the tree. I then went to open a lock at a chest in the wilderness, it wouldn’t unlock and when I checked the perk tree, this perk had disappeared at some point between drinking the potion and reaching the chest again.

**Comment by Styyx1** [comment]
they only work for 60 seconds. or even only for 30 i don't remember 
if your archaelogist perk wasn't removed afterwards then the mod actually has a bug and i prob will look at that at some point

**Comment by cinaedusmortiis** [comment]
Ohhh okay thanks for clarifying

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cinaedusmortiis** [comment]
Great modlist btw, i've loved playing it

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
