### ISSUE TITLE
'[BUG]' "SKSE Plugin Loader"

### ISSUE THREAD

**Issue by zioroiwi** [Styyx1/Ruvaak-Readme#26]
**modlist.txt**

https://pastebin.mozilla.org/0BXOOPOY

**Describe the bug**
Fisrt, sorry for this form, i'm not really good at English. So i'm just fresh install Ruvaak, but a popup say "A DLL plugin has failed to load correctly. If a new version of Skyrim was just released, the plugin needs to be updated. Please check the mod's webpage for updates." And after that is a list of 19 dll file like RaceMenuRotation.dll, RecursionFPSFix.dll, v.v... : couldn't load plugin (0000045A). If i chose to No button to ingore the warning, game crash. I had tried reinstall Skyrim and modlist but the same error.

**Expected behavior**
Game ran normal (?)

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug.

**Modlist version**

As Wabbajack say it's 4.1.1

**Did you add any additional mods?**

No, i'm just install this modlist.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

[modlist.txt](https://github.com/Styyx1/Ruvaak-Readme/files/12657639/modlist.txt)
![Untitled](https://github.com/Styyx1/Ruvaak-Readme/assets/70985002/07dfc265-24ac-4c54-aa1a-3425ecd6c074)

**Comment by Styyx1** [comment]
reinstall with Wabbajack cause it looks like something got corrupted during the install
